#!/bin/sh

set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
PREFIX_DIR="$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)"
APP_BIN="${PREFIX_DIR}/libexec/AcidDrop/AcidDrop"
APP_RES="${PREFIX_DIR}/share/AcidDrop"

exec "${APP_BIN}" -p "${APP_RES}" "$@"

